---
name: Docker Image CI

on:
  push:
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: buluma/almalinux

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          ignore: DL3003,DL3033,DL3059,DL3013,SC2039,SC2086,SC3037

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Goss
      uses: e1himself/goss-installation-action@v1.2.1

    - name: Build and Export
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: false
        load: true
        tags: ${{ env.IMAGE_NAME }}:8
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # - name: Test the Docker image
    #   run: docker run -it --rm --privileged --cgroupns=host --volume=/sys/fs/cgroup:/sys/fs/cgroup:rw ${{ env.IMAGE_NAME }}:9

  automerge:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]' || github.actor == 'buluma' && github.event_name == 'pull_request'}}
    steps:
      - uses: "actions/checkout@master"
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Merge Dependabot PR"
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: 
      - lint
      - test
      - automerge
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:8
          
